version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_case:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case  --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_case.feather

  generate_study_population_control:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control  --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_control.feather

  # generate_dataset_report_control:
  #   run: >
  #     dataset-report:v0.0.9
  #       --input-files output/data/input_control.feather
  #       --output-dir output/data
  #   needs: [generate_study_population_control]
  #   outputs:
  #     moderately_sensitive:
  #       dataset_report: output/data/*.html
  
  # generate_dataset_report_case:
  #   run: >
  #     dataset-report:v0.0.9
  #       --input-files output/data/input_case.feather
  #       --output-dir output/data
  #   needs: [generate_study_population_case]
  #   outputs:
  #     moderately_sensitive:
  #       dataset_report: output/data/*html

  data_bind:
    run: r:latest analysis/data_stack.R
    needs:
    - generate_study_population_case
    - generate_study_population_control
    outputs:
      highly_sensitive:
        input: output/input.feather

  data_process:
    run: r:latest analysis/data_process.R
    needs:
    - data_bind
    outputs:
      highly_sensitive:
        rds: output/data/data_processed.rds
        vaxlong: output/data/data_vaxlong.rds

  # skim_process:
  #   run: r:latest analysis/data_skim.R output/data/data_processed.rds output/data_properties
  #   needs:
  #   - data_process
  #   outputs:
  #     moderately_sensitive:
  #       cohort: output/data_properties/data_processed*.txt

  # data_process_long:
  #   run: r:latest analysis/data_process_long.R
  #   needs:
  #   - data_process
  #   outputs:
  #     highly_sensitive:
  #       processed: output/data/data_long*.rds

  # data_selection:
  #   run: r:latest analysis/data_selection.R
  #   needs:
  #   - data_process
  #   outputs:
  #     highly_sensitive:
  #       data: output/data/data_cohort.rds
  #       feather: output/data/data_cohort.feather
  #     moderately_sensitive:
  #       flow: output/data/flowchart.csv

  # skim_selection:
  #     run: r:latest analysis/data_skim.R output/data/data_cohort.rds output/data_properties
  #     needs:
  #     - data_selection
  #     outputs:
  #       moderately_sensitive:
  #         cohort: output/data_properties/data_cohort*.txt

  # cohort_report:
  #   run: cohort-report:v3.0.0 output/data/data_cohort.feather
  #   needs:
  #   - data_selection
  #   outputs:
  #     moderately_sensitive:
  #       html: output/data/reports/cohort/*.html
  #       png: output/data/reports/cohort/*.png
  #   config:
  #     output_path: output/data/reports/cohort/

      