version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_treated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_treated  --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_treated.feather
        
  data_process_treated:
    run: r:latest analysis/data_process_treated.R over12
    needs:
    - generate_study_treated
    outputs:
      highly_sensitive:
        rds: output/data/data_treated_eligible.rds
      moderately_sensitive:
        flowchart: output/data/flowchart_treated_eligible.csv


  ## matching round 1
  
  generate_study_control_potential1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_potential --output-format feather --index-date-range "2021-09-20 to 2021-09-20 by week"
    outputs:
      highly_sensitive:
        cohort: output/input_control_potential_2021-09-20.feather

 
  data_process_control_potential1:
    run: r:latest analysis/data_process_control.R over12 1
    needs:
    - generate_study_control_potential1
    outputs:
      highly_sensitive:
        rds: output/data/data_control_potential1.rds
 
  matching1:
    run: r:latest analysis/matching.R over12 1
    needs:
    - data_process_treated
    - data_process_control_potential1
    outputs:
      highly_sensitive:
        rds1: output/match/data_potential_matchstatus1.rds
        rds2: output/match/data_potential_matched1.rds
        csv: output/match/potential_matched_controls1.csv.gz
 
 
  generate_study_match_control1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_match1 --output-format feather
    needs:
    - matching1
    outputs:
      highly_sensitive:
        cohort: output/input_control_match1.feather 
  
  matching_filter1:
    run: r:latest analysis/matching_filter.R over12s 1
    needs:
    - matching1
    - generate_study_population_match_control1
    outputs:
      highly_sensitive:
        rds: output/match/match_data_matchstatus1.rds
        csv: output/match/potential_matched_controls1.csv.gz

      