version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_treated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_treated  --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_case.feather

  generate_study_population_control1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_control.feather

  # generate_dataset_report_control:
  #   run: >
  #     dataset-report:v0.0.9
  #       --input-files output/data/input_control.feather
  #       --output-dir output/data
  #   needs: [generate_study_population_control]
  #   outputs:
  #     moderately_sensitive:
  #       dataset_report: output/data/*.html
  
  # generate_dataset_report_case:
  #   run: >
  #     dataset-report:v0.0.9
  #       --input-files output/data/input_case.feather
  #       --output-dir output/data
  #   needs: [generate_study_population_case]
  #   outputs:
  #     moderately_sensitive:
  #       dataset_report: output/data/*html

  data_bind:
    run: r:latest analysis/data_stack.R
    needs:
    - generate_study_population_case
    - generate_study_population_control
    outputs:
      highly_sensitive:
        input: output/input.feather

  data_process:
    run: r:latest analysis/data_process.R
    needs:
    - data_bind
    outputs:
      highly_sensitive:
        rds: output/data/data_processed.rds

  # skim_process:
  #   run: r:latest analysis/data_skim.R output/data/data_processed.rds output/data_properties
  #   needs:
  #   - data_process
  #   outputs:
  #     moderately_sensitive:
  #       cohort: output/data_properties/data_processed*.txt

  # data_selection:
  #   run: r:latest analysis/data_selection.R
  #   needs:
  #   - data_process
  #   outputs:
  #     highly_sensitive:
  #       data: output/data/data_cohort.rds
  #       feather: output/data/data_cohort.feather
  #     moderately_sensitive:
  #       flow: output/data/flowchart.csv

  # skim_selection:
  #     run: r:latest analysis/data_skim.R output/data/data_cohort.rds output/data_properties
  #     needs:
  #     - data_selection
  #     outputs:
  #       moderately_sensitive:
  #         cohort: output/data_properties/data_cohort*.txt

  matching1:
    run: r:latest analysis/matching.R over12s 1
    needs:
    - data_process
    outputs:
      highly_sensitive:
        rds: output/match/data_potential_matchstatus1.rds
        rds: output/match/data_potential_matched1.rds
        csv: output/match/potential_matched_controls1.csv.gz
  
  generate_study_population_match_control1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_match_control --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_match_control1.feather
  
  matching_filter1:
    run: r:latest analysis/matching_filter.R over12s 1
    needs:
    - matching1
    - generate_study_population_match_control1
    outputs:
      highly_sensitive:
        rds: output/match/match_data_matchstatus1.rds
        csv: output/match/potential_matched_controls1.csv.gz

      